# (PART) Strategy analysis {-}
# Bin quality

```{r load_data_quality}
load("data/data.Rdata")
```

```{r bin_quality_biplot}
#Generate quality biplot
bin_metadata %>%
  select(genome,completeness,contamination,overall_strategy, assembly, size) %>%
  ggplot(aes(x=completeness,y=contamination,size=size,color=overall_strategy)) +
              geom_point(alpha=0.3, size=1.5) +
              scale_color_manual(values=strategy_colors)+
              ylim(c(10,0)) +
              labs(y= "Contamination", x = "Completeness") +
              theme_classic() +
              theme(legend.position = "none")
```

```{r completeness_barplot, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
bin_metadata %>%
  select(genome,completeness,contamination,overall_strategy, assembly, size) %>%
  mutate(assembly=factor(assembly,levels=assemblies)) %>%
  ggplot(aes(y=completeness,x=overall_strategy, group=overall_strategy, color=overall_strategy)) +
      geom_jitter(alpha=0.1)+
      geom_boxplot(outlier.shape = NA)+
              scale_color_manual(values=strategy_colors)+
              facet_grid(~assembly, space = "free", scale="free")+
              labs(x = "Strategies", y="Completeness") +
              theme_classic() +
              theme(legend.position = "none")
```

```{r completeness_density, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
bin_metadata %>%
  select(genome,completeness,contamination,overall_strategy, assembly, size) %>%
  ggplot(aes(x=completeness,color=assembly)) +
              geom_density(alpha=0.3, size=1.5, linewidth=1) +
              scale_color_manual(values=assembly_colors)+
              labs(x = "Completeness", y="Density") +
              theme_classic()
```

```{r contamination_barplot, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
bin_metadata %>%
  select(genome,completeness,contamination,overall_strategy, assembly, size) %>%
  mutate(assembly=factor(assembly,levels=assemblies)) %>%
  ggplot(aes(y=contamination,x=overall_strategy, group=overall_strategy, color=overall_strategy)) +
      geom_jitter(alpha=0.1)+
      geom_boxplot(outlier.shape = NA)+
              scale_color_manual(values=strategy_colors)+
              facet_grid(~assembly, space = "free", scale="free")+
              labs(x = "Strategies", y="Contamination") +
              theme_classic() +
              theme(legend.position = "none")
```

```{r contamination_density, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
bin_metadata %>%
  select(genome,completeness,contamination,assembly, size) %>%
  ggplot(aes(x=contamination,color=assembly,)) +
              geom_density(alpha=0.3, size=1.5, linewidth=1) +
              scale_color_manual(values=assembly_colors)+
              labs(x = "Contamination", y="Density") +
              theme_classic()
```

```{r GUNC, fig.height=4, fig.width=10, fig.fullwidth=TRUE}

gunc <- read_delim("data/gunc_summary.tsv")

gunc %>% 
  summarise(n = n(), .by = c(overall_strategy, pass.GUNC)) %>%
  ggplot(aes(x = overall_strategy, y = n, fill = pass.GUNC)) +
  geom_bar(stat = "identity", position = position_stack(reverse = FALSE)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, size = 14, hjust = 1),
        axis.text.y = element_text(size = 14),
        axis.title = element_text(size = 16, face = "bold")) +
  labs(y = "Number of bins", x = "Overall strategy")


gunc_fail <- gunc %>%
  filter(pass.GUNC == F) %>% 
  summarise(n_failed = n(), .by = overall_strategy)

gunc_pass <- gunc %>%
  filter(pass.GUNC == T) %>% 
  summarise(n_pass = n(), .by = overall_strategy)

gunc_fail %>%
  inner_join(., gunc_pass, by = join_by(overall_strategy)) %>%
  mutate(percent_passed_GUNC = (1 - (n_failed / n_pass)) * 100) %>%
  tt()


```


