# Alpha diversity

```{r load_data_alpha}
load("data/data.Rdata")
```

```{r alpha_diversity, comment="", message=FALSE, warning=FALSE, eval=FALSE}
alpha_div <- tibble()

for (strategy in strategies){
  bin_counts_norm_filt_strategy <- bin_counts_norm_filt %>%
    filter(overall_strategy == {{strategy}}) %>%
    select(secondary_cluster,sample,read_count) %>%
    pivot_wider(names_from = "sample", values_from = "read_count", values_fn = sum) %>%
    column_to_rownames(var="secondary_cluster")
    
  cluster_tree_strategy <- keep.tip(cluster_tree, tip=rownames(bin_counts_norm_filt_strategy))
  
  q0n <- bin_counts_norm_filt_strategy %>%
          hilldiv(.,q=0) %>% as.numeric()
  q1n <- bin_counts_norm_filt_strategy %>%
            hilldiv(.,q=1) %>% as.numeric()
  q1p <- bin_counts_norm_filt_strategy %>%
            hilldiv(.,q=1,tree=cluster_tree_strategy) %>% as.numeric()
  
  alpha_div_strategy <- tibble(strategy=strategy,sample=colnames(bin_counts_norm_filt_strategy),richness=q0n,neutral=round(q1n,3),phylo=round(q1p,3))
  alpha_div<- bind_rows(alpha_div,alpha_div_strategy)
}
save(alpha_div,file="results/alpha_diversity.Rdata")
```

```{r alpha_diversity_plot, comment="", message=FALSE, warning=FALSE}
load("results/alpha_diversity.Rdata")
alpha_div %>%
  pivot_longer(!c(strategy,sample),names_to = "metric",values_to = "value") %>%
  mutate(metric=factor(metric,levels=c("richness","neutral","phylo"))) %>%
  mutate(strategy=factor(strategy,levels=rev(strategies))) %>%
  ggplot(aes(y=strategy, x=value, color=strategy))+
    geom_boxplot(outlier.shape = NA)+
    geom_jitter(alpha=0.1)+
    scale_color_manual(values=strategy_colors)+
    facet_nested(. ~ metric, scales = "free") +
    theme_minimal() +
    labs(x="Diversity",y="Strategy") +
    theme(legend.position = "none")
```

```{r alpha_diversity_test_richness, comment="", message=FALSE, warning=FALSE}
load("results/alpha_diversity.Rdata")
alpha_test <- alpha_div %>%
  pivot_longer(!c(strategy,sample),names_to = "metric",values_to = "value") %>%
  mutate(strategy=factor(strategy,levels=strategies)) %>%
  filter(metric=="richness") %>%
  lmerTest::lmer(value ~ strategy + (1 | sample), data = .)

alpha_test %>%
  broom.mixed::tidy()

alpha_test %>%
  anova() %>%
  broom::tidy()
```

```{r alpha_diversity_test_neutral, comment="", message=FALSE, warning=FALSE}
load("results/alpha_diversity.Rdata")
alpha_test <- alpha_div %>%
  pivot_longer(!c(strategy,sample),names_to = "metric",values_to = "value") %>%
  mutate(strategy=factor(strategy,levels=strategies)) %>%
  filter(metric=="neutral") %>%
  lmerTest::lmer(value ~ strategy + (1 | sample), data = .)

alpha_test %>%
  broom.mixed::tidy()

alpha_test %>%
  anova() %>%
  broom::tidy()
```

```{r alpha_diversity_test_phylo, comment="", message=FALSE, warning=FALSE}
load("results/alpha_diversity.Rdata")
alpha_test <- alpha_div %>%
  pivot_longer(!c(strategy,sample),names_to = "metric",values_to = "value") %>%
  mutate(strategy=factor(strategy,levels=strategies)) %>%
  filter(metric=="phylo") %>%
  lmerTest::lmer(value ~ strategy + (1 | sample), data = .)

alpha_test %>%
  broom.mixed::tidy()

alpha_test %>%
  anova() %>%
  broom::tidy()
```