# Case study 2

```{r case2_community_kegg, comment="", message=FALSE, warning=FALSE}
community_kegg_list <- list()
for (strategy in strategies){
  cluster_kegg_strategy <- cluster_kegg %>%
    filter(overall_strategy == strategy) %>%
    select(-overall_strategy) %>%
    column_to_rownames(var="secondary_cluster")
  
  bin_counts_norm_filt_strategy <- bin_counts_norm_filt %>%
    mutate(timepoint=substr(sample,6,7)) %>%
    filter(timepoint %in% c("HT","CT")) %>%
    filter(secondary_cluster %in% rownames(cluster_kegg_strategy)) %>%
    select(secondary_cluster,sample,read_count) %>%
    pivot_wider(names_from = "sample", values_from = "read_count", values_fn = sum) %>%
    mutate(across(where(is.double), ~ ./sum(.)))
  
   community_kegg_table <- c()
   samples <- colnames(bin_counts_norm_filt_strategy)[-1]
   
  for(sample in samples){
    community_kegg <- colSums(sweep(cluster_kegg_strategy[bin_counts_norm_filt_strategy$secondary_cluster,],1,bin_counts_norm_filt_strategy %>% pull({{sample}}), FUN="*"))
    community_kegg_table <- rbind(community_kegg_table,community_kegg)
  }
   rownames(community_kegg_table) <- samples
   
   community_kegg_list[[strategy]] <- community_kegg_table
}
```

```{r case2_kegg_comparison, comment="", message=FALSE, warning=FALSE}
community_kegg_comparison_list <- list()
for (strategy in strategies){
  community_kegg_comparison<- community_kegg_list[[strategy]] %>%
    as.data.frame() %>%
    rownames_to_column(var="sample") %>%
    pivot_longer(!sample,names_to="trait",values_to="value") %>%
    mutate(animal=substr(sample,1,5)) %>%
    mutate(treatment=substr(sample,6,7)) %>%
    group_by(trait) %>%
    mutate(meanvalue=mean(value)) %>%
    filter(meanvalue>0.3) %>%
    mutate(model_result = list(lmerTest::lmer(value ~ treatment + (1 | animal)))) %>%
    ungroup() %>%
    select(trait,model_result) %>%
    unique() %>%
    mutate(estimate = map_dbl(model_result, ~broom.mixed::tidy(.) %>% filter(term == "treatmentHT") %>% pull(estimate))) %>%
    mutate(p_value = map_dbl(model_result, ~broom.mixed::tidy(.) %>% filter(term == "treatmentHT") %>% pull(p.value))) %>%
    mutate(p_value_adj = p.adjust(p_value, method = "bonferroni")) %>%
    select(trait, estimate, p_value_adj)
  
  community_kegg_comparison_list[[strategy]] <- community_kegg_comparison
}

all_p_values <- imap_dfr(community_kegg_comparison_list, ~ .x %>%
  mutate(strategy = .y))

all_p_values %>%
  mutate(trend=ifelse(p_value_adj<0.05 & estimate>0,"hot","neutral")) %>%
  mutate(trend=ifelse(p_value_adj<0.05 & estimate<0,"cold",trend)) %>%
  group_by(trait, trend) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  pivot_wider(values_from="count",names_from="trend") %>%
  tt()

#Maximum number of significances
all_p_values %>%
  mutate(trend=ifelse(p_value_adj<0.05 & estimate>0,"hot","neutral")) %>%
  mutate(trend=ifelse(p_value_adj<0.05 & estimate<0,"cold",trend)) %>%
  group_by(strategy, trend) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  pivot_wider(values_from="count",names_from="trend") %>%
  tt()
```

```{r case2_kegg_comparison_plot, comment="", message=FALSE, warning=FALSE, fig.height=4, fig.width=10, fig.fullwidth=TRUE}

functional_trends <- all_p_values %>%
  mutate(trend=ifelse(p_value_adj<0.05 & estimate>0,"hot","neutral")) %>%
  mutate(trend=ifelse(p_value_adj<0.05 & estimate<0,"cold",trend)) %>%
  select(trait,strategy,trend) %>%
  pivot_wider(names_from="trait",values_from = "trend") %>%
  column_to_rownames(var="strategy")

functional_tree <- all_p_values %>%
  select(-p_value_adj) %>%
  pivot_wider(names_from="trait",values_from="estimate") %>%
  column_to_rownames(var="strategy") %>%
  dist() %>%
  hclust() %>%
  ggtree()

gheatmap(functional_tree, functional_trends, offset=0.15, colnames=FALSE, width=8) +
  geom_tiplab(size=2, align=TRUE) +
  scale_fill_manual(values=c("#78bacf","#e0766e","#f4f4f4"))

```