# Beta diversity

```{r load_data_beta}
load("data/data.Rdata")
```

```{r beta_diversity, comment="", message=FALSE, warning=FALSE, eval=FALSE}
beta_div <- list()

n=0
for (strategy in strategies){
  n=n+1
  bin_counts_norm_filt_strategy <- bin_counts_norm_filt %>%
    filter(overall_strategy == {{strategy}}) %>%
    select(secondary_cluster,sample,read_count) %>%
    pivot_wider(names_from = "sample", values_from = "read_count", values_fn = sum) %>%
    column_to_rownames(var="secondary_cluster")
    
   cluster_tree_strategy <- keep.tip(cluster_tree, tip=rownames(bin_counts_norm_filt_strategy))
  
    beta_q0n <- bin_counts_norm_filt_strategy %>%
      hillpair(., q=0, metric="C") %>% as.dist()
    
    beta_q1n <- bin_counts_norm_filt_strategy %>%
      hillpair(., q=1, metric="C")
    
    beta_q1p <- bin_counts_norm_filt_strategy %>%
      hillpair(., q=1, metric="C", tree = cluster_tree_strategy)
  
  beta_div_strategy <- list(q0n=beta_q0n,q1n=beta_q1n,q1p=beta_q1p)
  beta_div[[n]] <- beta_div_strategy
}

names(beta_div) <- strategies
save(beta_div,file="results/beta_diversity.Rdata")
```
